# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "CentosCouchdb"
#  config.vm.box_url = "http://inzynieria.it/CentosCouchdb.box"
#  config.vm.box_url = "file://c:/devel/ra2k/CentosCouchdb.box"
#  config.vm.network "private_network",ip: "192.168.11.11"
  config.vm.network :forwarded_port, guest: 8888, host: 7777 
  config.vm.network :forwarded_port, guest: 80, host: 8081  
  config.vm.network :forwarded_port, guest: 5984, host: 5985
  
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "512"]
  end
end
